export const products = [
  {
    id: 1,
    name: "Premium Adjustable Dumbbells",
    category: "Equipment",
    price: 299.99,
    image: "/adjustable-dumbbells-fitness-equipment.jpg",
    description: "Professional-grade adjustable dumbbells with quick-change weight system",
    rating: 4.8,
    reviews: 234,
  },
  {
    id: 2,
    name: "Whey Protein Isolate",
    category: "Supplements",
    price: 49.99,
    image: "/protein-powder-supplement-container.jpg",
    description: "Pure whey protein isolate with 25g protein per serving",
    rating: 4.9,
    reviews: 567,
  },
  {
    id: 3,
    name: "Resistance Bands Set",
    category: "Equipment",
    price: 34.99,
    image: "/resistance-bands-fitness-equipment-set.jpg",
    description: "Complete set of 5 resistance bands for full-body workouts",
    rating: 4.7,
    reviews: 189,
  },
  {
    id: 4,
    name: "Pre-Workout Energy Boost",
    category: "Supplements",
    price: 39.99,
    image: "/pre-workout-supplement-powder.jpg",
    description: "Advanced pre-workout formula for maximum energy and focus",
    rating: 4.6,
    reviews: 423,
  },
  {
    id: 5,
    name: "Yoga Mat Pro",
    category: "Equipment",
    price: 59.99,
    image: "/premium-yoga-mat-fitness.jpg",
    description: "Extra-thick non-slip yoga mat with carrying strap",
    rating: 4.8,
    reviews: 312,
  },
  {
    id: 6,
    name: "BCAA Recovery Formula",
    category: "Supplements",
    price: 44.99,
    image: "/bcaa-supplement-powder-container.jpg",
    description: "Essential amino acids for muscle recovery and growth",
    rating: 4.7,
    reviews: 278,
  },
  {
    id: 7,
    name: "Kettlebell Set",
    category: "Equipment",
    price: 149.99,
    image: "/kettlebell-set-fitness-equipment.jpg",
    description: "Professional kettlebell set with 3 different weights",
    rating: 4.9,
    reviews: 156,
  },
  {
    id: 8,
    name: "Creatine Monohydrate",
    category: "Supplements",
    price: 29.99,
    image: "/creatine-powder.png",
    description: "Pure micronized creatine for strength and performance",
    rating: 4.8,
    reviews: 445,
  },
  {
    id: 9,
    name: "Pull-Up Bar",
    category: "Equipment",
    price: 79.99,
    image: "/pull-up-bar-doorway-fitness.jpg",
    description: "Heavy-duty doorway pull-up bar with multiple grip positions",
    rating: 4.6,
    reviews: 201,
  },
  {
    id: 10,
    name: "Multivitamin Complex",
    category: "Supplements",
    price: 24.99,
    image: "/multivitamin-supplement-bottle.jpg",
    description: "Complete daily multivitamin for active lifestyles",
    rating: 4.7,
    reviews: 389,
  },
  {
    id: 11,
    name: "Foam Roller",
    category: "Equipment",
    price: 39.99,
    image: "/foam-roller-fitness-recovery.jpg",
    description: "High-density foam roller for muscle recovery and massage",
    rating: 4.8,
    reviews: 267,
  },
  {
    id: 12,
    name: "Fat Burner Capsules",
    category: "Supplements",
    price: 54.99,
    image: "/fat-burner-supplement-bottle.jpg",
    description: "Thermogenic fat burner with natural ingredients",
    rating: 4.5,
    reviews: 334,
  },
]

export const reviews = [
  {
    id: 1,
    name: "Sarah Johnson",
    rating: 5,
    comment: "Amazing quality products! The adjustable dumbbells are a game-changer for my home gym.",
    product: "Premium Adjustable Dumbbells",
    date: "2025-03-15",
  },
  {
    id: 2,
    name: "Mike Chen",
    rating: 5,
    comment: "Best protein powder I've tried. Mixes well and tastes great!",
    product: "Whey Protein Isolate",
    date: "2025-03-10",
  },
  {
    id: 3,
    name: "Emily Rodriguez",
    rating: 4,
    comment: "Great resistance bands set. Perfect for travel workouts.",
    product: "Resistance Bands Set",
    date: "2025-03-08",
  },
  {
    id: 4,
    name: "David Thompson",
    rating: 5,
    comment: "This pre-workout gives me incredible energy without the crash. Highly recommend!",
    product: "Pre-Workout Energy Boost",
    date: "2025-03-05",
  },
]
